### ISSUE TITLE
Unexpected API Error

### ISSUE THREAD

**Issue by pkkid** [iboyperson/ulauncher-system#1]
Getting the below during installation of the extension:

Ubuntu 18.04.2 LTS
GNOME Shell 3.28.4
Ulauncher v4.4.0.r1

> Unexpected API error. GithubExtensionError: This extension is not compatible with current version Ulauncher extension API (v1.0.0)

**Comment by berkiyo** [comment]
I'm also getting the same error.

Fedora 30
GNOME Shell 3.32.2
Ulauncher v4.4.0.r1

**Comment by solrevdev** [comment]
same here

Ulauncher v4.4.0.r1

```shell
        `:+ssssssssssssssssss+:`           ------------------ 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 19.04 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: HP 250 G6 Notebook PC 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.0.0-21-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 hours, 27 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2462 (dpkg), 1 (pkg), 22 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.3 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 3.32.1 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: GNOME Shell 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-7200U (4) @ 3.100GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel HD Graphics 620 
      -+sssssssssssssssssyyyssss+-         Memory: 2631MiB / 7891MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       

```

**Comment by putu-eka-mulyana** [comment]
Unexpected API error. GithubExtensionError: This extension is not compatible with current version Ulauncher extension API (v1.0.0)

on ubuntu 19.04

**Comment by tjquillan** [comment]
Apologies for the late reply! To be quite honest I wasn't aware I didn't get notifications for this repository (should be fixed now). 

Anyway, This extension uses certain python features specific to python 3 which is only supported by the newer API v2.0.0.

I would advise [updating](https://ulauncher.io/#Download) your ULauncher as python 2.0 is going to hit end of life pretty [soon](https://pythonclock.org/)
