### ISSUE TITLE
it is nort working in peppermint 10 respin

### ISSUE THREAD

**Issue by anshace** [iboyperson/ulauncher-system#11]

**Comment by tjquillan** [comment]
Hi, can you provide any additional information on this? What is your system python version? You can find this by typing `python --version`. Additionally if you can give logs that would be very helpful. Thanks!

**Comment by tjquillan** [comment]
Hi, I just pushed a commit https://github.com/iboyperson/ulauncher-system/commit/ac5ed7842be2d471e7026cfd723f7c42d10f344b that might fix your problem if my hunch is correct. Please let me know if this persists.

**Comment by anshace** [comment]
python 3.9.1 
it is working now . thanks
