### ISSUE TITLE
instacrash on gnome 40

### ISSUE THREAD

**Issue by Doooooo0o** [iboyperson/ulauncher-system#15]
After upgrading to FC34 (wayland):

![image](https://user-images.githubusercontent.com/1903124/120292983-1a44e280-c2c5-11eb-8e98-c00d6cda65aa.png)

versions:
![image](https://user-images.githubusercontent.com/1903124/120293164-48c2bd80-c2c5-11eb-8658-2788b857d71f.png)

**Comment by tjquillan** [comment]
Hi, I pushed a potential fix. I do not have a Gnome 40 system to test on so can you confirm or deny this fix?

**Comment by Doooooo0o** [comment]
all good, thanks!
