### ISSUE TITLE
Support for more options

### ISSUE THREAD

**Issue by UltraBlackLinux** [iboyperson/ulauncher-system#16]
Hey there,
I'd love to see some support for more options (and maybe even custom ones) like `systemctl hybrid-sleep` - Hibernate and Suspend both have been acting up lately, but together they work fine - as well as support for customisations (Disabling modules, adding custom ones, ...)
Is this viable?
Thanks!

**Comment by tjquillan** [comment]
Hi, thanks for opening an issue. This extension currently supports custom configurations (see [here](https://github.com/tjquillan/ulauncher-system#configuration)) to add or modify entries and desktops (currently can't disable entries but I'll work on that). If you think any of the desktops or entries should be upstreamed I am always open to pull requests or feature requests. 

I will leave this issue open for now in case the instructions need clarification and / or until disabling entries is do-able.

**Comment by UltraBlackLinux** [comment]
> Hi, thanks for opening an issue. This extension currently supports custom configurations (see [here](https://github.com/tjquillan/ulauncher-system#configuration)) to add or modify entries and desktops (currently can't disable entries but I'll work on that). If you think any of the desktops or entries should be upstreamed I am always open to pull requests or feature requests.
> 
> I will leave this issue open for now in case the instructions need clarification and / or until disabling entries is do-able.

Oh XDG_CONFIG_HOME is unset for me, that's probably why there's no config to be found

**Comment by tjquillan** [comment]
When ` XDG_CONFIG_HOME` is undefined it defaults to `$HOME/.config` according to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

Also you can now disable entries which I have documented in the configuration section

**Comment by UltraBlackLinux** [comment]
> When ` XDG_CONFIG_HOME` is undefined it defaults to `$HOME/.config` according to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
> 
> Also you can now disable entries which I have documented in the configuration section

yeah I completely overread that.
I also just now discovered, that there are no config files in .config/ulauncher-system, but rather in .local/share/ulauncher/extensions/foobar/.
Thanks for your help!

**Comment by tjquillan** [comment]
Hi, I would not recommend changing configurations in the extensions folder as this could possibly affect updating the extension in the future (from my understanding ulauncher just pulls the repository to update). To modify configs I would instead recommend copying files from `.local/share/ulauncher/extensions/ulauncher-system` to `$HOME/.config/ulauncher-system` and then modifying them with the info in [configuration](https://github.com/tjquillan/ulauncher-system#configuration)
