### ISSUE TITLE
Crashed after udpate to gnome 40

### ISSUE THREAD

**Issue by marabesi** [iboyperson/ulauncher-system#18]
Hello there, just noticed that the ext is crashing after an updated I did to gnome 40 - I am not sure if this under this extension repo or ulaucher.

**Comment by tjquillan** [comment]
Hi thanks for reporting, if it is the extension that is crashing can you run ulauncher from the terminal and send the logs here? This will help me figure out what the issue is.

**Comment by marabesi** [comment]
I think this is the debug message:

![image](https://user-images.githubusercontent.com/2129872/146977041-ee5c2189-7939-45b4-a1f0-9b5788eba2e2.png)


````
2021-12-21 18:59:40,471 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.iboyperson.ulauncher-system" exited instantly with code 1
2021-12-21 18:59:40,472 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.iboyperson.ulauncher-system" failed with an error: ImportError: Requiring names
pace 'Gdk' version '3.0', but '4.0' is already loaded

````

**Comment by tjquillan** [comment]
Hi, can you verify you are running the latest of this extension? You can do that by telling ulauncher to check the extension for updates in the extensions window. I ask because I think this should have been fixed in https://github.com/tjquillan/ulauncher-system/commit/639facd8be9208afde0371def31913b0804709e8.

**Comment by marabesi** [comment]
You are correct, just forced the update and not it works again.

Thanks for your support.
