### ISSUE TITLE
Icons are not displayed

### ISSUE THREAD

**Issue by ChristianRegueiro** [iboyperson/ulauncher-system#21]
Hello, the icons for 'shut down', 'lock', etc doesn't show for some reason. I tried to reinstall the extension but i still have the same problem. A screenshot is attached to illustrate the problem.

![Screenshot from 2023-11-11 13-34-08](https://github.com/tjquillan/ulauncher-system/assets/67583927/4c4138c4-2252-49f9-9acd-0c6ba8dc2aec)

**Comment by tjquillan** [comment]
Hi,
ulauncher-system uses the system icon theme for its icons so it is likely an issue with that. I personally use [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) so my testing during development is done using that icon theme. Can you let me know what icon theme you are using so I can look more into this? Thanks!

**Comment by ChristianRegueiro** [comment]
I use the Fedora 39 gnome default icon theme.

**Comment by tjquillan** [comment]
Hi, I added some fallback icons in the event your icon theme does not have the icons that ulauncher-system needs. Please try updating the extension and let me know if this fixes your issue. Thanks!

**Comment by ChristianRegueiro** [comment]
It works perfect now. Thank you!

**Comment by tjquillan** [comment]
Glad to hear it! No problem!
