### ISSUE TITLE
How to customize system commands

### ISSUE THREAD

**Issue by Arteneko** [iboyperson/ulauncher-system#4]
I'm an i3 user, with custom commands for every action (using xdg-open, systemd power, etc).

I'd like to be able to easily customize system commands, e.g. through an ini/toml/json file in `$XDG_CONFIG_HOME/`.

Is the extension ready for that, or does it need work on that?

**Comment by tjquillan** [comment]
Apologies for the late reply. This would require work. After having a look at your fork I could see this feature looking something like I have shown below. This would allow the extension to ship default values of given IDs and for the config to allow the overriding of them if the user so chooses.

```
{
    "entries": {
        "<ID>": {
            "name": "",
            "description": "",
            "icon": "",
            "aliases": [""],
            "command": ""
        }
    }
}
```

**Example:**
```json
{
    "entries": {
        "lock": {
            "name": "Lock",
            "description": "Lock the session",
            "icon": "system-lock-screen",
            "aliases": ["lock"],
            "command": "dm-tool lock"
        }
    }
}
```

**Comment by tjquillan** [comment]
Closing as https://github.com/iboyperson/ulauncher-system/pull/5 should have addressed this issue. 

You can now write to a config file at `$XDG_CONFIG_HOME/ulauncher-system.json` for examples of what this file would look like reference the [entries directory](https://github.com/iboyperson/ulauncher-system/tree/master/entries) for the default and desktop specific configs shiped with ulauncher-system

Edit: Feel free to comment / re-open if you feel the PR does not adequately address this issue.
